src/Entity/Commande.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use App\Validator\Constraints as AcmeAssert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommandeRepository")
 * @AcmeAssert\VisitDays()
 */
class Commande
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Ce champ ne peux être vide !")
     */
    private $mail;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_visit;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_tickets;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $halfday;

    /**
     * @ORM\Column(type="integer" , nullable=true)
     */
        private $categorie;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Billet", mappedBy="commande", cascade={"persist"})
     */
    private $billets;

    /**
     * @ORM\Column(type="integer" , nullable=true)
     */
    private $prixTotal;


    public function __construct()
    {
        $this->billets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getDateVisit(): ?\DateTimeInterface
    {
        return $this->date_visit;
    }

    public function setDateVisit(\DateTimeInterface $date_visit): self
    {
        $this->date_visit = $date_visit;

        return $this;
    }

    public function getNbTickets(): ?int
    {
        return $this->nb_tickets;
    }

    public function setNbTickets(int $nb_tickets): self
    {
        $this->nb_tickets = $nb_tickets;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getHalfday(): ?bool
    {
        return $this->halfday;
    }

    public function setHalfday(bool $halfday): self
    {
        $this->halfday = $halfday;

        return $this;
    }

    /**
     * @return Collection|billet[]
     */
    public function getBillets(): Collection
    {
        return $this->billets;
    }

    public function addBillet(billet $billet): self
    {
        if (!$this->billets->contains($billet)) {
            $this->billets[] = $billet;
            $billet->setCommande($this);
        }

        return $this;
    }

    public function removeBillet(billet $billet): self
    {
        if ($this->billets->contains($billet)) {
            $this->billets->removeElement($billet);
            // set the owning side to null (unless already changed)
            if ($billet->getCommande() === $this) {
                $billet->setCommande(null);
            }
        }

        return $this;
    }

    /**
     * @return int|null
     */
    public function getCategorie(): ?int
    {
        return $this->categorie;
    }

    public function setCategorie(?int $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getPrixTotal()
    {
        $prixTotal = 0;
        foreach ($this->getBillets() as $billet){

            $prixTotal += $billet->getTarif();
        }
        return $prixTotal;
    }

    public function setPrixTotal(?int $prixTotal)
    {
        $this->prixTotal = $prixTotal;

        return $this;
    }

}

src/Controller/TicketController.php
<?php

namespace App\Controller;

use App\Entity\Billet;
use App\Entity\Commande;
use App\Form\BilletType;
use App\Form\CommandeType;
use App\Service\CheckNbTicket;
use App\Service\CheckPrice;
Use App\Service\Email;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\SessionInterface;



class TicketController extends AbstractController
{
    //Acceuil du site//
    /**
     * @param Request $request
     * @param SessionInterface $session
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/" , name="home")
     */


    public function home(Request $request, SessionInterface $session)
    {

        $session = $request->getSession ();
        return $this->render ('ticket/home.html.twig', [
            'title' => 'Bienvenue au Musée du Louvre'
        ]);
    }



    /**
     * @Route("/reservation_impossible" , name="reservation_impossible")
     */
    public function reservation_impossible(Request $request, EntityManagerInterface $em, CheckPrice $checkPrice)
    {
        return $this->render ('messages/reservation_impossible.html.twig', [

        ]);

    }

    /**
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/mentions" , name="mentions")
     */

    Public function mentions()
    {
        return $this->render ('ticket/mentions.html.twig', [
            'title' => "Les mentions légales"
        ]);
    }

    /**
     * @Route("/ticket1", name="ticket_phase_1")
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return \Symfony\Component\HttpFoundation\Response
     */

    public function ticket_1(Request $request, EntityManagerInterface $em)
    {

        $commande = new Commande();
        $session = $request->getSession ();
        $form = $this->createForm (CommandeType::class, $commande);
        $form->handleRequest ($request);


        if ($request->isMethod ('POST')) {
            if ($form->isSubmitted () && $form->isValid ()) {
                $session->set ("commande", $commande);
                $commande->setCreatedAt (new \DateTime());
                $visit = $commande->getDateVisit ();

                $em->persist ($commande);

                $repository = $em->getRepository (Commande::class);
                    $nb_tickets_on_day = $repository->getNbVisitors($visit);

                        if ($nb_tickets_on_day>1000)
                            {
                                $this->addFlash ("warning", "impossible pour cette date,le nombre de reservation possible est déja atteint. Veuillez retourner à l'accueil afin de reprendre votre commande, par avance merci !");
                                return $this->redirectToRoute ('reservation_impossible');
                            }
                        else
                            {
                            $this->addFlash ('success', "Etape suivante : Veuillez renseigner chaque ticket.");

                            return $this->redirectToRoute ('ticket_phase_2');
                            }
            } else
                return $this->render ('ticket/index.html.twig' , [
                    'title' => " Réservation en ligne",
                    'formCommande' => $form->createView ()
                ]);
        }

        return $this->render ('ticket/index.html.twig', [
            'title' => " Réservation en ligne",
            'formCommande' => $form->createView ()
        ]);
    }



    /**
     * @Route("/ticket2", name="ticket_phase_2")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */

    public function ticket_2(Request $request, EntityManagerInterface $em, CheckPrice $checkPrice)
    {

        $billet = new Billet();
        $session = $request->getSession ();
        $commande = $session->get ("commande");
        $nombre_tickets = $commande->getNbTickets ();

        $form = $this->createFormBuilder ();
        for ($i = 0; $i < $nombre_tickets; $i++) {
            $form->add ($i, BilletType::class, [
                'label' => "VISITEUR N°" . ($i + 1)])
                ->getForm ();
        }

        $formBillet = $form->getForm ();
        $formBillet->handleRequest ($request);
        $form->getData ();

        if ($request->isMethod ('POST')) {
            if ($formBillet->isSubmitted () && $formBillet->isValid ()) {
                $data = $formBillet->getData ();

                for ($i = 0; $i < $nombre_tickets; $i++) {
                    $commande->addBillet ($data[$i]);
                }

                return $this->redirectToRoute ('ticket_phase_3', [
                    'commande' => $commande
                ]);
            }
        }

        return $this->render ('ticket/ticket_phase2.html.twig', [
            'billet' => $billet,
            'title' => 'Choix du billet',
            'formBillet' => $formBillet->createView ()
        ]);
    }

    /**
     * @Route("/ticket3", name="ticket_phase_3")
     * @param Request $request
     * @param CheckPrice $checkPrice
     * @param EntityManagerInterface $em
     * @param Email $email
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Twig_Error_Loader
     * @throws \Twig_Error_Runtime
     * @throws \Twig_Error_Syntax
     */

    public function showOrder(Request $request, CheckPrice $checkPrice, EntityManagerInterface $em, Email $email)
    {
        $session = $request->getSession ();
        $commande = $session->get ("commande");
        $billet = $session->getId ();
        $billet = $checkPrice->generateBillets ($commande);
        $mail = $commande->getMail ();

        $session->set ('commande', $commande);
        $em->persist ($commande);
        $em->flush ();

        if ($request->isMethod ('POST')) {
            $token = $request->get ('stripeToken');
            try {
                \Stripe\Stripe::setApiKey ($this->getParameter ('stripe_secret_key'));
                \Stripe\Charge::create (array(
                    "amount" => $commande->getPrixTotal () * 100,
                    "currency" => "eur",
                    "source" => "$token",
                    "description" => "test premiere facturation"
                ));
            }catch (\Stripe\Error\Card $e)
            {
                $$this->addFlash ('refus', 'Votre paiement à été refusé veuillez saisir un autre numéro de carte');

                return $this->render ('ticket/ticket_phase3.html.twig',
                    array('commande' => $commande,
                        'stripe_public_key' => $this->getParameter ('stripe_public_key')));
            }

            $email->sendMail ($commande);
            $this->addFlash ('Success', 'Votre commande est bien enregistrée');


            return $this->redirectToRoute ('Merci');

        }

        return $this->render ('ticket/ticket_phase3.html.twig', [
            'mail' => $mail,
            'commande' => $commande,
            'billets' => $billet,
            'stripe_public_key' => $this->getParameter ('stripe_public_key')
        ]);
    }

    /**
     * @Route("/thanks", name="Merci"))
     *
     */
    public function thanks(Request $request, \Swift_Mailer $mailer)
    {
        $session = $request->getSession ();
        $commande = $session->get ("commande");
        $mail = $commande->getMail ();




        return $this->render ('remerciements/thanks.html.twig', [
            'title' => 'Merci pour votre future visite'
        ]);
    }
}

templates/ticket/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <br>
    <div class="titre-accueil">
        <h1>{{ title|upper }}</h1>
    </div>
    <br>
    <br>
    <div class="img-accueil">
        <img class="d-block w-100" src="{{ asset("images/louvre.jpg") }}" alt="First slide">
    </div>

    <br><br>
    <div class="button-access-billet">
     <a href="{{ path("ticket_phase_1") }}" class="btn btn-info" role="button">Acceder à la billeterie en ligne</a>
    </div>
    <br><hr>

    <div class="text-home">
        <div class="row">
            <div class="col-md-4 link1-2-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h5><i class="fa fa-fw fa-check"></i> {{ "Se rendre au musée"|trans|upper}}</h5>
                    </div>
                    <br>
                    <div class="panel-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
                        <div class="button-access-billet">
                        <p><a href="#" class="btn btn-info">{{ "Pour en savoir plus, c'est ici."|trans}}</a></p><br>
                        </div>
                    </div>
                </div>
            </div>

            <br>

            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h5 id="activity"><i class="fa fa-fw fa-check"></i> {{ 'Les expositions en cours'|trans|upper}}</h5>
                    </div>
                    <br>
                    <div class="panel-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
                        <div class="button-access-billet">
                        <p><a href="#" class="btn btn-info">{{ "Liste des expositions en cours"|trans}}</a></p>
                        </div>
                        <br>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h5 id="expo"><i class="fa fa-fw fa-check"></i> {{ "Les activités du musée"|trans|upper}}</h5>
                    </div>
                    <br>
                    <div class="panel-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
                        <div class="button-access-billet">
                        <a href="#" class="btn btn-info">{{ "Nos différentes activités"|trans}}</a>
                        </div>
                </div>
            </div>
        </div>
    </div>
    <br><br>
    <div class="row">
        <div id="gallery">
            <div class="slider">
                <a href="#">
                    <img src="images/mona-lisa.jpg"/>
                </a>
                <a href="#">
                    <img src="images/louvresphinx.jpg"/>
                </a>
                <a href="#">
                    <img src="images/woman.jpg"/>
                </a>
                <a href="#">
                    <img src="images/sculpture.jpg"/>
                </a>
                <a href="#">
                    <img src="images/erect-gravestone.jpg"/>

                </a>
                            </div>
            <div class="suivant">

            </div>
            <div class="precedent">

            </div>
        </div>
    </div>

{% endblock %}

templates/ticket/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    Billeterie en ligne
{% endblock %}
{% block body %}
    <body>
        <br>
        <div class="titre-accueil">
            <h1>CREATION DE VOTRE COMMANDE</h1>
               <h2>Veuillez remplir les informations ci-après :</h2>
        </div>
            <div class="formulaire-1">
            <br>
                {{ form_start(formCommande) }}
                    {{ form_widget(formCommande) }}
                        <button type="submit" class="button-access-billet2" >Etape suivante</button>
                {{ form_end(formCommande) }}
            </div>
    </body>
{% endblock %}

templates/ticket/mentions.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h1>{{ title }}</h1>

    <p>
        Bienvenue sur le site du musée du Louvre.

        Ancien palais des rois, le Louvre épouse l’histoire de France depuis huit siècles. Conçu dès sa création en 1793 comme un musée universel, ses collections,
        qui figurent parmi les plus belles au monde, couvrent plusieurs millénaires et un territoire qui s’étend de l’Amérique aux frontières de l’Asie.
        Réparties en huit départements, elles contiennent des œuvres universellement admirées, comme La Joconde, la Victoire de Samothrace ou la Vénus de Milo.
        Le Louvre est aujourd’hui le musée le plus visité au monde.

        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis nibh tincidunt, volutpat tellus vitae, vulputate neque. Proin ornare, nisi eu rhoncus lacinia, leo ex facilisis nisi, condimentum imperdiet quam ex ac lectus. Praesent diam mauris, rutrum in velit ut, laoreet vehicula elit. Curabitur sit amet ornare diam, id venenatis mi. Pellentesque in congue metus, ac mollis nisl. Pellentesque iaculis posuere gravida. Fusce nulla libero, euismod vitae augue ac, consectetur vulputate ex. Quisque at vulputate turpis. Suspendisse id nulla mauris. Aliquam ornare orci eget ligula iaculis sollicitudin. Nullam feugiat congue arcu vitae lobortis.

        Donec eget placerat nisl. Integer vulputate quis risus aliquam fermentum. Pellentesque tincidunt sollicitudin auctor. Nam mattis velit nunc, et lacinia sapien euismod sed. Proin facilisis blandit elementum. Proin tortor eros, vulputate sit amet accumsan nec, tincidunt aliquam ante. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec mollis ultricies purus, pharetra volutpat ipsum. Sed id metus sit amet metus scelerisque efficitur. Etiam tristique consectetur lectus at commodo. Morbi quis arcu purus. Donec luctus lorem libero, sit amet rhoncus magna eleifend ut. Donec viverra ac nunc eget sagittis.

        Praesent eget enim erat. Praesent convallis, sapien id ullamcorper ultricies, orci ipsum maximus felis, non efficitur erat augue ut nisi. Nunc volutpat sodales tristique. Pellentesque vel ultricies leo, non sagittis arcu. Aenean at leo nisl. Praesent ac ultrices ante, vitae venenatis lorem. Nam ultricies, sem in maximus dignissim, lectus arcu blandit ligula, ac semper enim libero et libero. Etiam eleifend sapien ut enim dictum, et dignissim risus egestas. Nullam accumsan porta sapien, nec pulvinar velit finibus in.

        Donec aliquam tincidunt lorem, non congue erat posuere eu. Pellentesque diam libero, tempor at consequat sit amet, tincidunt in metus. Sed vitae viverra nunc. In condimentum sapien vitae tempus hendrerit. Donec et ante sed magna blandit pretium ut ac augue. Vestibulum in erat in purus venenatis rhoncus quis at enim. Nunc mollis arcu eu lorem ullamcorper, quis facilisis risus sollicitudin.

        Nam scelerisque nisl tellus, nec convallis diam sagittis sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur orci quam, facilisis sit amet porta id, tincidunt et neque. Praesent vitae orci nec tortor interdum eleifend. Maecenas volutpat pharetra urna, ut dapibus enim feugiat non. Proin vitae neque risus. Integer vestibulum, eros ut tristique tempus, magna lorem cursus ipsum, a pulvinar odio elit non mauris. In nibh diam, pharetra quis viverra ut, finibus id velit. Donec auctor lectus sed efficitur aliquam. Etiam auctor tristique sem, ac euismod enim faucibus a. Morbi blandit porttitor nunc non vestibulum. Praesent feugiat, diam ac congue volutpat, orci ipsum porttitor sem, vitae varius elit ligula quis ligula. Curabitur ac risus vel lectus fringilla cursus.
    </p>


{% endblock %}

templates/ticket/ticket_phase2.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<body>
        {% for msg in app.session.flashbag.get('success') %}
            <div class="alert alert-success">
                {{ msg }}
            </div>
        {% endfor %}
        <div class="fa-2x">
            <div class="titre-accueil">
            <h2>CREATION DE VOTRE COMMANDE ETAPE 2</h2>
            </div>
                <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <h3>Veuillez remplir les informations ci-après :</h3>

                                {{  form_start(formBillet) }}
                                {{ form_errors(formBillet) }}
                                {{ form_widget(formBillet) }}
                                <button type="submit" class="button-access-billet2" >Etape suivante</button>
                                {{ form_end(formBillet) }}


                        </div>
                    </div>
                </div>
            <br>
        </div>
</body>
{% endblock %}

templates/ticket/ticket_phase3.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <body>

        <div class="container">
            {% for msg in app.session.flashbag.get('success') %}
                <div class="alert alert-success">
                    {{ msg }}
                </div>
            {% endfor %}
            <h1>RESUME DE VOTRE COMMANDE</h1>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Email</th>
                            <th>Date de la commande</th>
                            <th>Date de visite</th>
                            <th>Nombre de tickets</th>
                        </tr>
                    </thead>
                        <tbody>
                                <tr>
                                    <td>{{ commande.mail }}</td>
                                    <td>{{ commande.createdAt|date('d-m-Y') }}</td>
                                    <td>{{ commande.dateVisit|date('d-m-Y') }}</td>
                                    <td>{{ commande.nbTickets }}</td>
                                </tr>
                        </tbody>
                </table>
             </div>
                <div class="pull-right">
                    <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-check"></i> {{ "RESUME DES TICKETS"|trans}}</h4>
                    </div>
                        <div class = "row">
                            <div class="col-xs-12 col-sm-12">
                                <div class="jumbotron">
                                        {%  for billet in commande.billets %}
                                            <hr color="white">
                                            <ul>NOM DU VISITEUR : {{ billet.name|e }}</ul>
                                            <ol>PRENOM DU VISITEUR: {{ billet.surname|e }}</ol>
                                            <ol>TARIF DU BILLET: {{ billet.tarif }} Euros</ol>
                                            <ol>CODE DE VERIFICATION UNIQUE: {{ billet.codeBillet}}</h4></ol>
                                            <hr color="white">
                                        {% endfor %}
                                </div>
                                <div class="col-xs-12 col-sm-6" style="display:flex; margin-left : 400px;">
                                    <form action="" method="POST">
                                        <script
                                                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                                data-key="{{ stripe_public_key }}"
                                                data-amount="{{ commande.PrixTotal*100 }}"
                                                data-name="Billetterie en ligne"
                                                data-description="Musée du Louvre"
                                                data-image="{{ asset ('images/Visage.png')}}"
                                                data-locale="fr"
                                                data-currency ="EUR">
                                        </script>
                                    </form>
                                </div>
                             </div>
                        </div>
                    </div>
            </div>
        </div>
         <br/>
    </body>
{%  endblock %}
{% block javascripts %}
{% endblock %}